"""Devorbit Multi-LLM SDK.

A unified Python SDK for multiple LLM providers with a Claude SDK-like interface.
"""

from ._agent_tools import (
    AgentCoordinator,
    AgentTask,
    TaskPriority,
    TaskResult,
    TaskStatus,
    cleanup_tasks,
    get_agent_info,
    get_all_agent_tools,
    list_active_tasks,
    list_agent_types,
    task,
    task_cancel,
    task_status,
)
from ._bash_tools import (
    bash,
    bash_output,
    cleanup_sessions,
    get_all_bash_tools,
    kill_shell,
    list_active_sessions,
)
from ._beta import AsyncBeta, Beta
from ._builtin_tools import (
    BASH_TOOL,
    COMPUTER_USE_TOOL,
    TEXT_EDITOR_TOOL,
    create_bash_tool,
    create_computer_use_tool,
    create_text_editor_tool,
    get_all_builtin_tools,
)
from ._client import AsyncDevorbit, Devorbit
from ._commands import (
    Command,
    CommandRegistry,
    execute_command,
    get_all_command_tools,
    list_slash_commands,
    load_commands,
    parse_command_invocation,
    register_command,
    run_slash_command,
)
from ._config import (
    DevorbitConfig,
    get_all_config_tools,
    load_config,
    read_config,
    save_config,
    update_config,
)
from ._errors import (
    APIConnectionError,
    APIError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    DevorbitError,
    InternalServerError,
    NotFoundError,
    OverloadedError,
    PermissionDeniedError,
    ProviderError,
    RateLimitError,
    StreamError,
    UnprocessableEntityError,
    UnsupportedProviderError,
)
from ._file_tools import (
    edit_file,
    get_all_file_tools,
    ls_directory,
    multi_edit_file,
    read_file,
    write_file,
)
from ._hooks import (
    Hook,
    HookContext,
    HookRegistry,
    HookType,
    PythonHookHandler,
    clear_hooks,
    disable_hooks,
    enable_hooks,
    execute_hook,
    execute_hooks,
    get_all_hook_tools,
    get_registry,
    hook,
    list_hooks,
    load_hooks_from_config,
    register_hook,
    trigger_hook,
    unregister_hook,
)
from ._mcp import MCPClient, MCPManager, MCPServerConfig, load_mcp_config
from ._models import (
    BatchRequestCounts,
    BatchResult,
    ContentBlockDeltaEvent,
    ContentBlockStartEvent,
    ContentBlockStopEvent,
    DocumentBlock,
    MessageBatchResponse,
    MessageDeltaEvent,
    MessageResponse,
    MessageStartEvent,
    MessageStopEvent,
    TextBlock,
    ThinkingBlock,
    TokenCountResponse,
    ToolUseBlock,
    Usage,
)
from ._notebook_tools import (
    NotebookCell,
    NotebookContent,
    NotebookReadResult,
    create_notebook_edit_tool,
    create_notebook_read_tool,
    get_all_notebook_tools,
    notebook_edit,
    notebook_read,
)
from ._planning import (
    PlanningState,
    cancel_plan,
    enter_planning_mode,
    exit_plan_mode,
    get_all_planning_tools,
    get_current_plan,
    get_planning_status,
    is_planning_active,
)
from ._plugins import (
    BasePlugin,
    DevorbitPlugin,
    LoadedPlugin,
    PluginMetadata,
    PluginRegistry,
    disable_plugin,
    discover_all_plugins,
    enable_plugin,
    get_all_plugin_tools,
    get_plugin_registry,
    get_plugin_tools,
    list_plugins,
    load_and_initialize_plugin,
)
from ._recovery import (
    ErrorCategory,
    ErrorClassifier,
    ErrorInfo,
    RecoveryManager,
    RecoveryStrategy,
    RetryConfig,
    RetryHandler,
    get_recovery_manager,
    reset_recovery_manager,
    with_retry,
)
from ._search_tools import get_all_search_tools, glob_files, grep_code
from ._skills import (
    Skill,
    SkillRegistry,
    execute_skill,
    get_all_skill_tools,
    get_skill_registry,
    list_available_skills,
    load_skills,
    register_skill,
    run_skill,
    validate_skill,
)
from ._todo_tools import (
    clear_todo_state,
    get_all_todo_tools,
    get_current_todos,
    todo_read,
    todo_write,
)
from ._tool_helpers import ToolExecutor, beta_tool, gather_tools
from ._types import (
    BashTool,
    BatchCreateParams,
    BatchRequest,
    BatchStatus,
    CacheControl,
    ComputerUseTool,
    ContentBlock,
    DocumentContent,
    DocumentSource,
    ImageContent,
    Message,
    MessageCreateParams,
    ProviderType,
    StopReason,
    TextContent,
    TextEditorTool,
    Tool,
    ToolChoice,
    ToolResultContent,
    ToolUseContent,
)
from ._web_tools import (
    WebFetchResult,
    WebSearchResult,
    create_web_fetch_tool,
    create_web_search_tool,
    get_all_web_tools,
    html_to_markdown,
    web_fetch,
    web_fetch_sync,
    web_search,
    web_search_sync,
)


__version__ = "0.1.0"

__all__ = [
    # Agent/Subagent Tools
    "AgentCoordinator",
    "AgentTask",
    "TaskPriority",
    "TaskResult",
    "TaskStatus",
    "cleanup_tasks",
    "get_agent_info",
    "get_all_agent_tools",
    "list_active_tasks",
    "list_agent_types",
    "task",
    "task_cancel",
    "task_status",
    # Built-in Tools
    "BASH_TOOL",
    "COMPUTER_USE_TOOL",
    "TEXT_EDITOR_TOOL",
    "create_bash_tool",
    "create_computer_use_tool",
    "create_notebook_edit_tool",
    "create_notebook_read_tool",
    "create_text_editor_tool",
    "create_web_fetch_tool",
    "create_web_search_tool",
    # Errors
    "APIConnectionError",
    "APIError",
    "APIStatusError",
    "APITimeoutError",
    "AuthenticationError",
    "BadRequestError",
    "DevorbitError",
    "InternalServerError",
    "NotFoundError",
    "OverloadedError",
    "PermissionDeniedError",
    "ProviderError",
    "RateLimitError",
    "StreamError",
    "UnprocessableEntityError",
    "UnsupportedProviderError",
    # Main Clients
    "AsyncBeta",
    "AsyncDevorbit",
    "Beta",
    "Devorbit",
    # Configuration
    "DevorbitConfig",
    "load_config",
    "read_config",
    "save_config",
    "update_config",
    "get_all_config_tools",
    "Hook",
    "HookContext",
    "HookRegistry",
    "HookType",
    "PythonHookHandler",
    "clear_hooks",
    "disable_hooks",
    "enable_hooks",
    "execute_hook",
    "execute_hooks",
    "get_all_hook_tools",
    "get_registry",
    "hook",
    "list_hooks",
    "load_hooks_from_config",
    "register_hook",
    "trigger_hook",
    "unregister_hook",
    "ErrorCategory",
    "ErrorClassifier",
    "ErrorInfo",
    "RecoveryManager",
    "RecoveryStrategy",
    "RetryConfig",
    "RetryHandler",
    "get_recovery_manager",
    "reset_recovery_manager",
    "with_retry",
    # Plugins
    "BasePlugin",
    "DevorbitPlugin",
    "LoadedPlugin",
    "PluginMetadata",
    "PluginRegistry",
    "disable_plugin",
    "discover_all_plugins",
    "enable_plugin",
    "get_all_plugin_tools",
    "get_plugin_registry",
    "get_plugin_tools",
    "list_plugins",
    "load_and_initialize_plugin",
    # Types
    "BashTool",
    "BatchCreateParams",
    "BatchRequest",
    "BatchRequestCounts",
    "BatchResult",
    "BatchStatus",
    "CacheControl",
    "ComputerUseTool",
    "ContentBlock",
    "ContentBlockDeltaEvent",
    "ContentBlockStartEvent",
    "ContentBlockStopEvent",
    "DocumentBlock",
    "DocumentContent",
    "DocumentSource",
    "ImageContent",
    "Message",
    "MessageBatchResponse",
    "MessageCreateParams",
    "MessageDeltaEvent",
    "MessageResponse",
    "MessageStartEvent",
    "MessageStopEvent",
    "ProviderType",
    "StopReason",
    "TextBlock",
    "TextContent",
    "TextEditorTool",
    "ThinkingBlock",
    "TokenCountResponse",
    "Tool",
    "ToolChoice",
    "ToolExecutor",
    "ToolResultContent",
    "ToolUseBlock",
    "ToolUseContent",
    "Usage",
    # MCP Support
    "MCPClient",
    "MCPManager",
    "MCPServerConfig",
    "load_mcp_config",
    # Commands
    "Command",
    "CommandRegistry",
    "execute_command",
    "get_all_command_tools",
    "list_slash_commands",
    "load_commands",
    "parse_command_invocation",
    "register_command",
    "run_slash_command",
    # Notebooks
    "NotebookCell",
    "NotebookContent",
    "NotebookReadResult",
    "get_all_notebook_tools",
    "notebook_edit",
    "notebook_read",
    # Planning
    "PlanningState",
    "cancel_plan",
    "enter_planning_mode",
    "exit_plan_mode",
    "get_all_planning_tools",
    "get_current_plan",
    "get_planning_status",
    "is_planning_active",
    # Skills
    "Skill",
    "SkillRegistry",
    "execute_skill",
    "get_all_skill_tools",
    "get_skill_registry",
    "list_available_skills",
    "load_skills",
    "register_skill",
    "run_skill",
    "validate_skill",
    # Bash Tools
    "bash",
    "bash_output",
    "cleanup_sessions",
    "get_all_bash_tools",
    "kill_shell",
    "list_active_sessions",
    # File Tools
    "edit_file",
    "get_all_file_tools",
    "ls_directory",
    "multi_edit_file",
    "read_file",
    "write_file",
    # Search Tools
    "get_all_search_tools",
    "glob_files",
    "grep_code",
    # Todo Tools
    "clear_todo_state",
    "get_all_todo_tools",
    "get_current_todos",
    "todo_read",
    "todo_write",
    # Web Tools
    "WebFetchResult",
    "WebSearchResult",
    "get_all_web_tools",
    "html_to_markdown",
    "web_fetch",
    "web_fetch_sync",
    "web_search",
    "web_search_sync",
    # Tool Helpers
    "beta_tool",
    "gather_tools",
]
